### GET Todas las solicitudes (Verificación Inicial)
GET http://localhost:8080/api/solicitudes

### POST - Registrar Solicitud (Asignará ID automáticamente)
POST http://localhost:8080/api/solicitudes
Content-Type: application/json

{
    "titulo": "No puedo iniciar sesión en la VPN",
    "descripcion": "El sistema me dice 'Credenciales Inválidas' desde ayer.",
    "cliente": {
        "nombre": "Javier Solís",
        "email": "javier.s@techcorp.com"
    },
    "prioridad": 5
}

### GET - Consultar Solicitud Específica (ID 1, 2 o 3 precargadas)
GET http://localhost:8080/api/solicitudes/1

### PUT - Actualizar Solicitud (Ejemplo para ID 1)
PUT http://localhost:8080/api/solicitudes/1
Content-Type: application/json

{
    "titulo": "Fallo de conexión a internet (actualizado)",
    "descripcion": "No puedo acceder a internet ni por cable ni por wifi.",
    "cliente": {
        "nombre": "Rodolfo Gonzales",
        "email": "rodolfo.g@tech.com"
    },
    "prioridad": 4
}

### DELETE - Eliminar Solicitud (Ejemplo para ID 1)
DELETE http://localhost:8080/api/solicitudes/1
